apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "resource-limits" 
spec:
  limits:
    -
      type: "Pod"
      max:
        cpu: "6" 
        memory: "10Gi" 
      min:
        cpu: "400m" 
        memory: "6Mi" 
    -
      type: "Container"
      max:
        cpu: "6" 
        memory: "10Gi" 
      min:
        cpu: "100m" 
        memory: "4Mi" 
      default:
        cpu: "3000m" 
        memory: "1000Mi" 
      defaultRequest:
        cpu: "2000m" 
        memory: "1000Mi" 
      maxLimitRequestRatio:
        cpu: "10"