apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: image-management
spec:
  params: 
    - name: TLSVERIFY
      description: Verify the TLS on the registry endpoint 
      type: string
      default: 'true' 
  resources:
    outputs:
      - name: output-image
        type: image
  steps:
    - name: push-image-to-openshift
      command:
        - buildah
        - push
        - '--tls-verify=$(params.TLSVERIFY)'
        - '$(resources.outputs.output-image.url):latest'
      image: registry.redhat.io/rhel8/buildah
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers

  volumes:
    - emptyDir: {}
      name: varlibcontainers