apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: open-liberty-image-stream
  namespace: pipeline-work
spec:
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/pipeline-work/open-liberty-image-stream
  type: image 