apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: petstoregitrepo
  namespace: pipeline-work
spec:
  params:
  - name: url
    value: https://github.com/marrober/petstore-jee7.git
  type: git