apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build
spec:
  params:
    - name: PATH_CONTEXT
      description: xxxxxx
      type: string
      default: .
    - name: MAVEN_ARGS_APPEND
      description: Additional Maven arguments
      type: string
      default: ''
    - name: MAVEN_MIRROR_URL
      description: The base URL of a mirror used for retrieving artifacts
      type: string
      default: ''   
    - name: MAVEN_CLEAR_REPO
      description: Remove the Maven repository after the artifact is built
      type: string
      default: 'false'   
    - name: TLSVERIFY
      description: Verify the TLS on the registry endpoint 
      type: string
      default: 'true' 
  resources:
    inputs:
      - name: source
        type: git
    outputs:
      - name: image
        type: image
  steps :
    - name: gen-env-file
      command:
        - /bin/sh
        - '-c'
      args:
        - |-
          echo "MAVEN_CLEAR_REPO=$(params.MAVEN_CLEAR_REPO)" > env-file

          [[ '$(params.MAVEN_ARGS_APPEND)' != "" ]] &&
            echo "MAVEN_ARGS_APPEND=$(params.MAVEN_ARGS_APPEND)" >> env-file

          [[ '$(params.MAVEN_MIRROR_URL)' != "" ]] &&
            echo "MAVEN_MIRROR_URL=$(params.MAVEN_MIRROR_URL)" >> env-file

          echo "Generated Env file"
          echo "------------------------------"
          cat env-file
          echo "------------------------------"
      image: registry.redhat.io/ocp-tools-43-tech-preview/source-to-image-rhel8
      volumeMounts:
        - name: envparams
          mountPath: /env-params
      workingDir: /env-params
    - name: generate
      command:
        - s2i
        - build
        - $(params.PATH_CONTEXT)
        - registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
        - '--image-scripts-url'
        - 'image:///usr/local/s2i'
        - '--as-dockerfile'
        - /gen-source/Dockerfile.gen
        - '--environment-file'
        - /env-params/env-file
      image: registry.redhat.io/ocp-tools-43-tech-preview/source-to-image-rhel8
      volumeMounts:
        - name: gen-source
          mountPath: /gen-source
        - name: envparams
          mountPath: /env-params
      workingDir: /workspace/source
    - name: view-workspace
      command:
        - ls
        - -al
        - /workspace
      image: registry.redhat.io/ocp-tools-43-tech-preview/source-to-image-rhel8
      volumeMounts:
        - name: gen-source
          mountPath: /gen-source
    - name: build
      command:
        - buildah
        - bud
        - '--tls-verify=$(params.TLSVERIFY)'
        - '--layers'
        - '-f'
        - /gen-source/Dockerfile.gen
        - '-t'
        - $(resources.outputs.image.url)
        - .
      image: registry.redhat.io/rhel8/buildah
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
        - name: gen-source
          mountPath: /gen-source
      workingDir: /gen-source
    - name: gen-binary-extraction-dockerfile
      command:
        - /bin/sh
        - '-c'
      args:
        - |-
          echo "FROM $(resources.outputs.image.url)" > ext-dockerfile.gen
          echo "RUN cp /tmp/src/target/applicationPetstore.war /envparams/Petstore.war" >> ext-dockerfile.gen
          echo "------------------------------"
          cat ext-dockerfile.gen
          echo "------------------------------"
      image: registry.redhat.io/ocp-tools-43-tech-preview/source-to-image-rhel8
      volumeMounts:
        - name: envparams
          mountPath: /env-params
      workingDir: /env-params
    - name: extract-built-object
      command:
        - buildah
        - bud
        - '--tls-verify=$(params.TLSVERIFY)'
        - '--layers'
        - '-f'
        - ext-dockerfile.gen
        - .
      image: registry.redhat.io/rhel8/buildah
      resources: {}
      securityContext:
        privileged: true
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
        - name: envparams
          mountPath: /env-params
      workingDir: /env-params
    - name: view-workspace-after-copy
      command:
        - ls
        - -al
      image: registry.redhat.io/ocp-tools-43-tech-preview/source-to-image-rhel8
        - name: envparams
          mountPath: /env-params
      workingDir: /env-params
  volumes:
    - emptyDir: {}
      name: envparams
    - emptyDir: {}
      name: gen-source
    - emptyDir: {}
      name: varlibcontainers