apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: secrets-test
spec:
  steps:
    - name: run-commands
      image: registry.redhat.io/rhel8/buildah
      script: |
        #!/usr/bin/env bash

        buildah login --authfile /workspace/dest/.docker/config.json default-route-openshift-image-registry.apps.cluster-daiwa-dd27.daiwa-dd27.example.opentlc.com

        buildah login --get-login default-route-openshift-image-registry.apps.cluster-daiwa-dd27.daiwa-dd27.example.opentlc.com

      volumeMounts:
        - name: pipeline-auth
          mountPath: /workspace/dest/.docker/
  volumes:
    - name: pipeline-auth
      secret:
        secretName: deployer-dockercfg-8ltrb
        items:
          - key: .dockercfg
            path: config.json